### ISSUE TITLE
換頁時需回到頂端

### ISSUE THREAD

**Issue by ddio** [g0v/summit2020#21]
## 重現方式：

1. 進到首頁
2. 往下捲幾下
3. 點選交通
4. 期待可以看到地圖，但發現已經在後面的各場地介紹了，捲軸沒有捲回最上面

**Comment by dwatow** [comment]
解好了，點擊時，執行原生寫法，強制讓 scroll 到頂

**Comment by ddio** [comment]
感謝～解完的話可以幫忙把這張票關掉呦～

另外，如果方便的話，可以在 commit log 裡標上 #21 ，就可以在這裡顯示相關的 commit 是哪些。

**Comment by Su-Ya** [comment]
改完推上才看到『 commit log 裡標上 #21 』，我修改一下 commit 在關閉

**Comment by ddio** [comment]
目前新 layout 沒有這個狀況，所以把這張票關掉囉～
