### ISSUE TITLE
更友善的使用者座標請求

### ISSUE THREAD

**Issue by ddio** [g0v/summit2020#22]
目前一進到交通頁時，瀏覽器就會跳出請求使用者座標的視窗，但並沒有說明索取座標的目的。

改善方式：

1. 只有在用到時，而且需要先讓使用者知道使用的目的，才請求座標
2. 可參考 [2018 選舉看板](https://ddio.github.io/election-board-map/)

**Comment by dwatow** [comment]
我試著把 `navigator.geolocation` 放到點擊連結時再執行。
但是卻一直報錯。 navigator is notdefined

```

  methods: {
    gmapLink (destination) {
      navigator.geolocation && navigator.geolocation.getCurrentPosition(({ coords }) => (this.hereCoords = [coords.latitude, coords.longitude]))
      const origin = this.hereCoords.join()
      return origin && `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}&hl=zh-tw`
    },
```
報錯
```
 ERROR  [Vue warn]: Error in render: "ReferenceError: navigator is not defined"

found in

---> <Pages/transport.vue> at pages/transport.vue
       <Nuxt>
         <Layouts/default.vue> at layouts/default.vue
           <Root>
```
![image](https://user-images.githubusercontent.com/1825852/83829133-c8e72f00-a714-11ea-923d-f8111ddb51ca.png)

查了一下，似乎是這個原因？
https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties

但是不知道怎麼改？

**Comment by ddio** [comment]
因為要讓 nuxt 每頁都跑自己的 head ，nuxt mode 從 `SPA` 改成 [`universal`](https://nuxtjs.org/api/configuration-mode/)，所以 nuxt 會用 node 跑部份的 vue life cycle ，包含 render html, created() 等等。

因此，如果在 node 會執行到的程式碼裡，參了只有瀏覽器環境才有的東西，像是 `navigator`, `windwo.xxx` 都會是 undefined 。

常見的解法是
1. html 的話，用 [<client-only>](https://nuxtjs.org/api/components-client-only/) 跳過 node render
2. method 的話，放在 mounted 或它之後的 life cycle hook 裡

目前的 master 已經把 transport + open-street-map 都加上 `client-only` 了。

如果試不原因，可以上個 PR 一起來看看～感謝！

**Comment by dwatow** [comment]
服用
https://nuxtjs.org/faq/window-document-undefined/

```
methods: {
 doSomething() {
    if (process.client) {
      // 寫在這
    }
  }
}
```

上傳了

**Comment by dwatow** [comment]
手機版是不是點不到 map link 了？
