### ISSUE TITLE
首頁的時間軸在手機上會滿出視窗

### ISSUE THREAD

**Issue by ddio** [g0v/summit2020#23]
寬度 410px 以下就會發生：

![Screenshot_20200604-214547](https://user-images.githubusercontent.com/271157/83764925-1e87f100-a6ad-11ea-8778-87c38e246efd.png)

**Comment by chihaoyo** [comment]
https://github.com/g0v/summit2020/commit/bacb42c6eeefc74168803d57f3e63abfe222c824 可以算解決了嗎 😛

**Comment by ddio** [comment]
有道理 XD
