### ISSUE TITLE
顯示英語系習慣的日期表達方式

### ISSUE THREAD

**Issue by ddio** [g0v/summit2020#40]
![2020-07-01 14-31-32 的螢幕擷圖](https://user-images.githubusercontent.com/271157/86210762-bba05180-bba7-11ea-8ea4-2ce6c4399146.png)

目前的日期表達方式是台灣慣用格式，例如 6/30 ，但英語系國家的習慣好像（？）不是如此

**Comment by rockleona** [comment]
剛剛做了修正
目前長這樣
![1595068654497](https://user-images.githubusercontent.com/34214497/87850841-d30c6800-c925-11ea-9f12-4eb270a89c20.jpg)

**Comment by ddio** [comment]
感謝！看起來不錯，唯一一點可以改進的是，因為這個日期只會使用在議程頁面，之後有機會時，可以將設定檔從全域的 en.js 一到 Agenda.vue 裡，用 i18n yaml 來寫，可以減少日後維護全域語系檔的成本。

另外，雖然這個專案沒有強制要求，但通常認領 github issue 的流程會是這樣：

1. 把 issue 指定給自己，讓其他人知道你正在處理，避免重工，和知道要和誰討論
2. commit 時，issue ID 之前要空格，例如 `Fixed for issue #40, changed date format. ` ，讓 github 可以把 commit 連到這則 issue 上
3. 可以使用 feature branch ，也就是先在本地端開一個新的 branch 完成功能，再將 branch 推上來後，建立一個 pull request ，例如 #33 ，這樣就可以找人確認還有沒有需要修改的地方，而不會直接改到大家都在用的程式碼

這兩件事都是降低維護、溝通成本的好習慣，雖然短期內要上手，可能會多一些麻煩，但有機會可以試試看呦～

**Comment by rockleona** [comment]
原來如此!! 學到了好多!!
