### ISSUE TITLE
講者頁

### ISSUE THREAD

**Issue by ddio** [g0v/summit2020#92]
https://app.zeplin.io/project/5f1eb392c8a8b237c06b8879/screen/5fa13052584b1817596b6c17

**Comment by KennethTsang9286** [comment]
這個需要幫手嗎？我見有幾個issue的超連結都不是公開的

**Comment by ddio** [comment]
感謝 @KennethTsang9286 ! 講者頁因為有些設計、資料細節，是在工人群組討論的，所以我來處理就可以，感謝你！！

話說你會去 Summit 嗎？想要認識跑來幫忙貢獻網址程式的大大～～

**Comment by KennethTsang9286** [comment]
@ddio 我身處海外，去不了Summit，只是路過這個repo，順便睇下幫唔幫到忙
